apiVersion: v1
kind: Pod
metadata:
  name: db-client-pod
  labels:
    name: db-client
spec:
  volumes:
  - name: prod-secret-volume
    secret:
      secretName: prod-db-secret
  - name: test-secret-volume
    secret:
      secretName: test-db-secret
  containers:
  - name: prod-client-container
    image: busybox
    command:
      - top
    volumeMounts:
    - name: prod-secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
  - name: test-client-container
    image: busybox
    command:
      - top
    volumeMounts:
    - name: test-secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
