apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
  namespace: default
  labels:
    app: http-probe
spec:
  containers:
    - name: probe
      image: aisxyz/k8s-demo
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          port: 8080
          path: /health
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
        timeoutSeconds: 4
