apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
spec:
  containers:
    - name: html-generator
      image: aisxyz/fortune
      imagePullPolicy: IfNotPresent
      #args: ["5"]
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-cfg
              key: sleep-interval
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - name: web-server
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs/
          readOnly: true
      ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
  volumes:
    - name: html
      emptyDir:
        medium: Memory
    - name: config
      configMap:
        name: fortune-cfg
        items:
          - key: my-nginx.conf
            path: https.conf
    - name: certs
      secret:
        secretName: fortune-https
