apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  volumes:
    - name: html
      emptyDir:
        medium: Memory
  containers:
    - name: html-generator
      image: aisxyz/fortune
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - name: web-server
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
          name: http
